[project]
name = "llm-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "tiktoken>=0.10.0",
    "torch>=2.8.0",
    "transformers>=4.55.0",
]
